# Generated by Django 4.1 on 2022-10-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('pointCum', models.DecimalField(decimal_places=2, default=0, max_digits=9000)),
            ],
        ),
        migrations.CreateModel(
            name='Concurent_par_manche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsCum', models.IntegerField(default=0)),
                ('concurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concurent')),
            ],
        ),
        migrations.CreateModel(
            name='Manche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('isopen', models.BooleanField(default=True)),
                ('concurent', models.ManyToManyField(to='core.concurent_par_manche')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervenant', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=2)),
                ('rank', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'manche'), (2, 'chant'), (3, 'jeu'), (4, 'slam'), (5, 'danse'), (6, 'Piece de Theatre')])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enoncee', models.TextField()),
                ('reponse', models.TextField()),
                ('number', models.IntegerField()),
                ('repondu', models.BooleanField()),
                ('manche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manche')),
                ('receveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personne_posee', to='core.concurent')),
                ('repliques', models.ManyToManyField(related_name='persone_avoir_repondu', to='core.concurent')),
                ('repliques_rate', models.ManyToManyField(to='core.concurent')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('p', 'primary'), ('s', 'success'), ('i', 'info'), ('w', 'warning'), ('d', 'danger')], max_length=1)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.concurent')),
            ],
        ),
        migrations.CreateModel(
            name='Dedicace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emetteur', models.CharField(max_length=100)),
                ('recepteur', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like_counter', models.IntegerField(default=0)),
                ('replique_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dedicace')),
            ],
        ),
    ]
