# Generated by Django 4.1 on 2023-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='nom',
            field=models.CharField(default='isaraelite', max_length=50),
            preserve_default=False,
        ),
    ]
