# Generated by Django 4.1 on 2023-08-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_concurent_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
