# Generated by Django 4.1 on 2022-10-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dedicace_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='icon',
        ),
    ]
