# Generated by Django 4.1 on 2023-08-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_concurent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='core.member'),
        ),
    ]
