# Generated by Django 4.1 on 2022-10-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_programme_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='passe',
            field=models.BooleanField(default=True),
        ),
    ]
