# Generated by Django 4.1 on 2023-08-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_concurent_coach'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='CustomEvent',
        ),
    ]
