# Generated by Django 4.1 on 2022-10-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programme_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='passe',
            field=models.BooleanField(default=False),
        ),
    ]
