# Generated by Django 4.1 on 2022-10-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_programme_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='type',
            field=models.IntegerField(choices=[(1, 'Manche'), (2, 'Chant'), (3, 'Jeu'), (4, 'Slam'), (5, 'Danse'), (6, 'Piece de Theatre')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='receveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personne_posee', to='core.concurent'),
        ),
        migrations.AlterField(
            model_name='question',
            name='repliques',
            field=models.ManyToManyField(blank=True, null=True, related_name='persone_avoir_repondu', to='core.concurent'),
        ),
        migrations.AlterField(
            model_name='question',
            name='repliques_rate',
            field=models.ManyToManyField(blank=True, null=True, to='core.concurent'),
        ),
    ]
