# Generated by Django 4.1 on 2023-08-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_event_customevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='mc',
            field=models.CharField(default='Sara Casseus', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='is_risk',
            field=models.BooleanField(default=False),
        ),
    ]
