# Generated by Django 4.1 on 2022-10-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_programme_type_alter_question_receveur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
