# Generated by Django 4.1 on 2023-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customevent_mc_question_is_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
