# Generated by Django 4.1.3 on 2022-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='id_fake',
            field=models.CharField(default='2389A1', max_length=50),
        ),
        migrations.AlterField(
            model_name='concurent',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='concurent',
            name='prenom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
