# Generated by Django 4.1.3 on 2022-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_concurent_id_fake_alter_concurent_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_answer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
