# Generated by Django 4.1 on 2023-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='otherPoint',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AddField(
            model_name='concurent',
            name='slogan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AddField(
            model_name='concurent',
            name='talent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
    ]
