# Generated by Django 4.1.3 on 2022-11-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_time_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsCum', models.FloatField()),
                ('manche', models.IntegerField()),
                ('concurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concurent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
    ]
