# Generated by Django 4.1.3 on 2022-11-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
