# Generated by Django 4.1.3 on 2022-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
