# Generated by Django 4.1 on 2022-12-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_question_is_unique_remove_question_repliques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_repliques',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='repliques',
        ),
        migrations.AddField(
            model_name='question',
            name='repliques',
            field=models.ManyToManyField(blank=True, null=True, related_name='persone_avoir_repondu', to='core.concurent'),
        ),
    ]
