# Generated by Django 4.1 on 2022-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_question_is_repliques_remove_question_repliques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='repliques',
            field=models.ManyToManyField(related_name='persone_avoir_repondu', to='core.concurent'),
        ),
        migrations.AlterField(
            model_name='question',
            name='repliques_rate',
            field=models.ManyToManyField(to='core.concurent'),
        ),
    ]
