# Generated by Django 4.1 on 2022-12-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fake_user_user_alter_fake_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeau',
            name='is_redeem',
        ),
        migrations.RemoveField(
            model_name='cadeau',
            name='question',
        ),
        migrations.AddField(
            model_name='cadeau',
            name='nombre_disponible',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dedicace',
            name='like_counter',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_redeem', models.BooleanField(default=False)),
                ('cadeau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadeau')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fake_user')),
            ],
        ),
    ]
