# Generated by Django 4.1 on 2022-12-21 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_cadeau_is_redeem_remove_cadeau_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeau_quesion',
            name='cadeau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsts', to='core.cadeau'),
        ),
    ]
