# Generated by Django 4.1 on 2022-12-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cadeau_quesion_cadeau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeau',
            name='is_answered',
        ),
    ]
